### ISSUE TITLE
Site Purpose 

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#1]
As a visiting user I can easily find out what the purpose of the website is and learn more about the site owner and the products being sold so that I can decide to stay and browse or not

## Acceptance Criteria:
a) The first thing the user should see on entering the website is an image which sets the tone of the website and a tagline explaining the purpose of the website
b)  Below the main image, there should be a section explaining to users what the website is for, and introducing the website owner who makes the products
c) There should be a 'Shop now' button which will link to the shop, the primary purpose of the website

## Tasks:
- [ ] Create base.html & index.html in Home App with the images and content
- [ ] Add appropriate CSS
- [ ] Test manually to ensure links work
