### ISSUE TITLE
View all Products

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#10]
As a site user I can easily view all the products in the shop so that I can see all the available products immediately without having to sort or filter or take any action

## Acceptance Criteria:
a) When a user goes to the Shop page, they are presented with all products on the page
b) The user does not have to do anything, the default is that all products are listed
c) Only products that are 'active' should be displayed
d) The details shown for each product should be: name, image, price, category

## Tasks:
- [ ] Create Products App, add the project level URL, add to installed apps in settings.py
- [ ] Create category model and product model, make migrations
- [ ] Create Template folder with templates
- [ ] Create view to display page as well as link URL
- [ ] Test all views
- [ ] Test the models
