### ISSUE TITLE
Search by Category 

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#12]
As a site user I can select a specific category of product so that I can view just the items in that category to make it easier to make a decision

## Acceptance Criteria:
a) In the shop page menu bar, there are menu options to choose a particular category
b) When a particular category is chosen, only the products in that category are displayed
c) The options are the categories currently set up by the store owner: T-Shirt, Hoodie, Jacket etc. There should also be an ALL category (which the shop page defaults to, but will be needed for the user if they want to go back to seeing all products after selecting a category)
d) User is able to filter by ticker e.g. ETH, BTC, ADA to find crypto-specific items of clothes

## Tasks:
- [ ] Menu for shop page should be created #14 . Add category options to menu
- [ ] Update show_products() view to check if there is a request to filter by category, and to return the products in that category if there is
- [ ] Update the links in the products.html and product_details.html for categories
- [ ] Test functionality
