### ISSUE TITLE
Sort products in shop

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#13]
As a site user I can sort the products in the shop so that I can find what I'm looking for easier

## Acceptance Criteria:
a) There is an option in the shop page menu bar to sort products
b) The user can choose one of these options, and the products are sorted according to the choice
c) The choices should be: by product name (A to Z), by product name (Z to A), by price (low to high), by price (high to low)

## Tasks:
- [ ] Add a sub header to the shop pages, where the sorting option dropdown will be shown
- [ ] Add any CSS if needed
- [ ] Update the show_products() view to check if sorting was requested, and to return the products that match the search
- [ ] Create script to update the URL based on the selected option - so that get request passed to view
- [ ] Test the functionality
