### ISSUE TITLE
Search for a product in the shop

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#14]
As a site user I can search for a product in the shop so that I can find a particular item quickly

## Acceptance Criteria:
a) There is a search box at the top of the shop page
b) The user can enter a search term and the page will display products that match
c) The search should return if the word is in the product name or description
d) If nothing is found, should tell the user that search came with no results

## Tasks:
- [ ] Create header/menu bar for Shop page, that will hold the search box (as well as category options - see #12 ) 
- [ ] Add the search form to the menu
- [ ] Style the menu and make sure it is responsive
- [ ] Update show_products() view to check if the search term returns a product and display
