### ISSUE TITLE
Add item to cart

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#16]
As a **site user** I can **add an item to my cart** so that **I can buy it**

## Acceptance Criteria:
a) From the product details page, a user can click on the Add to Bag button, to add an item to their bag
b) The subtotal underneath the Bag icon in the header should update to show the new total in the bag
c) User should be able to add unlimited items to bag

## Tasks:
- [ ] Create Bag App, add to INSTALLED_APPS and Project level URLS
- [ ] Create bag.html template, URL and basic view
- [ ] Create contexts.py to store the bag items context so it is accessible to entire site, add to settings.py
- [ ] Create view to add to bag (create URL to match)
- [ ] Update the form in product_details.html to use this view
- [ ] Test the functionality - manual testing needs to be done in conjunction with #19
