### ISSUE TITLE
Select quantity of item to add to cart

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#17]
As a site user I can select the quantity of an item before adding to my cart so that I can add multiple of that item at once

## Acceptance Criteria:
a) From the product details page, a user can select the quantity to buy, before pressing the Add to Bag button
b) The user can either use the + and - buttons beside the input box, or can type into the input box
c) The user should not be able to input less than 1 or more than 99 of an item 
d) The updated subtotal appears in the cart when the quantity is changed

## Tasks:
- [ ] Write the JavaScript to handle increasing and decreasing the value in the input box
- [ ] Add min and max values to input in the html template
- [ ] Write script to disable the + / - buttons if value is outside the range of min/max range
- [ ] Test functionality
- [ ] Update cart so it shows the updated sub total for each item
