### ISSUE TITLE
See items in cart

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#19]
As a site user I can see the items in my cart at any time so that I can check what I have already added to the cart

## Acceptance Criteria:
a) A user can click on the Bag icon from the header and this brings them to a page showing the items that they have added to the bag
b) There is a message if no items have been added, with button to return to shop
c) The details shown for each item in the cart are: product details (image + product name), price, quantity and subtotal
d) Underneath the listed items is a total, delivery charge amount and subtotal

## Tasks:
- [ ] Update cart.html (#16) to show the details
- [ ] View should be created in #16 when bag app when created
- [ ] Add CSS a required
- [ ] Add logic to show message if no items in cart
- [ ] Add delivery threshold to settings.py and contexts.py so delivery can be calculated
- [ ] Update cart link in header to link to cart.html page
- [ ] Test function
