### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#2]
As a site user I can navigate the site so that I can find the page I want to go to

## Acceptance Criteria:
a) There should be a site header which is at the top of every page on the website
b) The logo (website name) should be prominent in the header and it should link back to the home page
c) The header should contain navigation links to all the pages within the shop

## Tasks:
- [ ] Create base.html template and create header inside this, add any CSS necessary
- [ ] Create mobile-nav-header.html for viewing on mobile
- [ ] Test the functionality
