### ISSUE TITLE
Adjust quantity of item in bag

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#20]
As a site user I can adjust the quantity of a particular item in the cart so that I can buy more or less of the item directly from the cart

## Acceptance Criteria:
a) When a user is viewing the bag page, there are quantity buttons shown for each item
b) The user can use the quantity +/- to adjust the quantity and update the amount of the item in the cart, and the totals update accordingly
c) The same quantity rules apply as before, except quantity can be 0 to remove the item

## Tasks:
- [ ] Add the input group for quantity input + / - buttons to the bag.html page
- [ ] Wire up the script that was written for #17 as this will need the same functionality
- [ ] Add a link/button to submit the new quantity so that totals update / product is removed if quantity = 0
- [ ] Create the view to handle adjusting the quantity / removing an item
- [ ] Ensure cart shows updated bag total
