### ISSUE TITLE
Remove item for cart

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#21]
As a site user I can remove an item from my cart so that I do not have to buy it if I've changed my mind

## Acceptance Criteria:
a) When a user is on the bag page, there is a button/link beside each item in the cart to remove that item
b) Once they click the button/link, the item is removed and the totals update accordingly
c) If this was the only item in the bag, then the page shows the message for when a bag is empty

## Tasks:
- [ ] Add link / button to remove the item
- [ ] Create view to remove item, and wire it up with the URL
- [ ] Write JavaScript to handle the click event and post the form
- [ ] Test functionality
