### ISSUE TITLE
Proceed to checkout

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#22]
As a site user I can continue to the checkout process once I've decided on my purchase so that I can buy the items

## Acceptance Criteria:
a) The user can click on the Checkout button on the cart page, to bring them to the checkout page
b) On the checkout page there is a form for the user to fill in their personal info and delivery details
c) There is also a section for payment details

## Tasks:
- [ ] Create Checkout App, add to INSTALLED_APPS, add to project level URL
- [ ] Create Order model to hold order details, and OrderLineItem model to hold each cart item details
- [ ] Add model methods to create order number and calculate totals
- [ ] Run Migrations
- [ ] Create signals.py and add functions to listen for line items being saved or deleted, so that totals can be updated
- [ ] Create OrderForm
- [ ] Create the Checkout view and add URL 
- [ ] Create template to show the form
- [ ] Add CSS
- [ ] Test functionality
