### ISSUE TITLE
Complete Purchase

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#23]
As a site user I can enter my delivery and payment details so that I can complete my purchase

## Acceptance Criteria:
a) On the checkout page, the user can enter their details into the form including payment details and then securely submit the payment
b) If the card details are invalid, an error message will appear
c) While the form is processing, page shows that is loading by adding an overlay

## Tasks:
- [ ] Add Stripe JavaScript in the base.html
- [ ] Add JavaScript to create the card element and add it to the checkout form payment details section 
- [ ] Add CSS to page
- [ ] Add button to checkout form
- [ ] Add listener to card element so that it checks for errors and shows errors to the user
- [ ] Install Stripe
- [ ] Create Stripe environments variables, add them to settings.py, import to View
- [ ] Update checkout view to calculate the total cart amount for stripe and create the payment intent
- [ ] Add listener to submit event on checkout form, to prevent submit and send info to stripe + disable the card element
- [ ] Update checkout view to create the order in database
- [ ] Create loading overlay div in checkout.html and add CSS
