### ISSUE TITLE
Order Confirmation

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#26]
As a site user I can see an order confirmation page so that I know that the order went through okay

## Acceptance Criteria:
a) After checkout, the user is redirected to a success page confirming the order was successful
b) The page shows all the order details - order number, date, the items in the order (qty and price), delivery address, and the totals for the order

## Tasks:
- [ ] Create checkout_success.html template to display the details
- [ ] Add CSS
- [ ] Create the view and add the URL path
- [ ] Update the checkout view (#23) to redirect to checkout_success on successful completion of payment
- [ ] Test the View
