### ISSUE TITLE
Receive order confirmation email

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#27]
As a site user I can receive an email confirmation of my order so that I have this confirmation for my records

## Acceptance Criteria:
a) After a user (either anonymous or logged in) successfully places an order, they receive an email confirming the details
b) The email contains the Order number and shop name in the subject box
c) The email body thanks the user for their order, and confirms the order date, totals and delivery info.

## Tasks:
- [ ] Create the .txt files for the email subject and body
- [ ] Write the method in the webhook handler to render .txt file and send the confirmation email 
- [ ] Update the payment_intent_succeeded to send the email if the order s found, or if the order is created
- [ ] Add default sending email to settings.py
- [ ] Test functionality
