### ISSUE TITLE
Find relevant social media accounts

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#3]
As a user I can find the sites social media accounts so that I can follow them on social media to keep up to date with the business

## Acceptance Criteria:
a) The links to the social media accounts should be in the footer on each page, represented by their icons
b) The links are external, so open in a new window
c) The links are for the Facebook business page, Twitter, Instagram and LinkedIn

## Tasks:
- [ ] Create footer in base.html
- [ ] Add social media links
- [ ] Complete the CSS
- [ ] Manually test to ensure links open in new tab
- [ ] Create Facebook Business Page and add screenshot to README.md
