### ISSUE TITLE
Sign up for an account

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#30]
As a site user I can sign up for an account so that I can enjoy the benefits of having an account with the site

## Acceptance Criteria:
a) The sign up page opens after the user clicks on link from header to sign up
b) The sign up form contains the fields for the user to register - username, email address, email address confirmation, password, confirm password and Submit button
c) The form doesn't submit unless the required fields are completed or if there are errors in the inputs
d) After the form is submitted successfully, the email verification page is displayed, see ####

## Tasks:
- [ ] Install allauth, set up allauth URLs, add to settings, run migrations
- [ ] Update header in base.html with the URL to sign up
- [ ] Amend the allauth templates so that styling matches rest of site
