### ISSUE TITLE
Receive email on sign up 

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#31]
As a site user I want to receive an email confirmation when I register so that I know my account registration was successful and secure

## Acceptance Criteria:
a) After filling in the sign up form (see #30 ) the user is redirected to a page confirming an email was sent for them to verify their email address
b) There should be an email received by that email address, providing a link to be used to verify the email address
c) The link brings the user to a new page where they can press a button to confirm the email address
d) After pressing the button, the user is brought to the sign in page to sign in

## Tasks:
- [ ] Set up app password on email account to send emails
- [ ] Add password and email host address to heroku config vars
- [ ] Update settings.py to use the email host in production/continue to print to terminal in dev
- [ ] Update domain name and display name for site in admin site, so it displays on the emails
- [ ] Deploy to Heroku
