### ISSUE TITLE
Login to Account

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#32]
As a registered user I can sign into my account so that I can access my profile to view all past orders

## Acceptance Criteria:
a) The sign in page opens after the user clicks on link from header to sign in
b) The sign up form contains the fields for the user to sign in - username or email address, and password - and Sign in button
c) After submitting the form, the user is redirected to the home page

## Tasks:
- [ ] Allauth should be installed as part of #30 and template styling done
- [ ] Add link to sit header in base.html for sign in  
- [ ] Update settings to ensure page redirects after sign in
