### ISSUE TITLE
Log Out of account

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#33]
As a registered user I can sign out of my account when finished so that I know I am signed out securely

## Acceptance Criteria:
a) When a user is signed in, the Sign Out link is present in the header from underneath the Account section
b) After clicking the Sign Out link, the Sign Out page opens
c) Sign Out page has text asking user to confirm they want to sign out
d) After signing out, the user is redirected to the home page

## Tasks:
- [ ] Update site header in base.html to show sign out link when user is signed in
- [ ] Update settings with sign out redirect url 
- [ ] Style allauth templates ensuring they are responsive
- [ ] Test functionality
