### ISSUE TITLE
Know if user is signed in or not

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#34]
As a registered user I can easily see if I am signed into my account or not so that I know straight away if I need to sign in

## Acceptance Criteria:
a) When a user is not signed in, there is a menu item in the main page navigation called Sign In. This menu item changes to 'Account' when the user is signed in (and the menu dropdown items change accordingly)
b) When the user is signed in, the header contains a note that they are "signed in as username"
c) When signed in, the My Profile page shows the user's name
d) On the checkout page, if the user is not signed in there is a note telling them they can sign in to use their saved default delivery info. (If they are signed in, then their default delivery info if any is populated on the delivery details, as per #25 )

## Tasks:
- [ ] Update the header in base.html to show the user name when signed in
- [ ] Check other pages to ensure content still visible now the header has an extra row 
- [ ] Style as appropriate
- [ ] Update profile.html to show the username
- [ ] Update checkout.html to show note if not signed in
