### ISSUE TITLE
View details of previous order

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#37]
As a registered user I can view details of a previous order so that I can check what was ordered and where it was delivered to

## Acceptance Criteria:
a) A logged in user who has previous orders can go to their order history and click on an order to view the full details
b) The details displayed are the same as those displayed in the checkout success page.

## Tasks:
- [ ] Update profile page to include a link to the order details and create URL
- [ ] Create the view for the order detail, using the checkout_success.html template since it contains the same information 
- [ ] Include a note that this is a past order not a current one
