### ISSUE TITLE
Navigation within My Account Section

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#38]
As a registered user I can easily navigate within the My Account pages so that I understand what pages are available and can get to them easily and I know what page I am on

## Acceptance Criteria:
a) When a logged in user is on the My Account pages (My Profile) there is a breadcrumb menu at the top showing them where they are, e.g. My Account - > My Profile

## Tasks:
- [ ] Add HTML to create breadcrumb navigation
- [ ] Add CSS as needed
- [ ] Ensure navigation is responsive
