### ISSUE TITLE
Admin able to view all products in shop

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#39]
As a website owner I can view all the products in the shop, even if they are not active, so that I can see an overview of all products, and so that I can edit inactive products

## Acceptance Criteria:
a) When a superuser is logged in, they can see all items in the shop, even those that are not active
b) The card for each product also displays the active status (this is not shown on the normal view for regular or anonymous users)

## Tasks:
- [ ] Update the products html template, to include the is_active flag in the card for each product, if the user is a superuser
- [ ] Update the view to show all products if the user is a superuser
- [ ] Also need to update product_details.html template to show is_active flag for superuser
- [ ] And update product_details view to ensure that a non superuser cannot access a url to view a non active product
