### ISSUE TITLE
Sign up to newsletter 

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#4]
As a site user I can sign up to the newsletter so that I can stay informed and stay engaged with the shop

## Acceptance Criteria:
a) The footer on each page should contain a form to sign up for the newsletter
b) The form consists of one field for email address, and a button to sign up
c) After submitting the form, the email address submitted is added to the subscribers list in Mail Chimp

Note: needs deployed website URL before Mail Chimp can be set up

## Tasks:
- [ ] Create Mail Chimp HTML and CSS to embed
- [ ] Tidy JS and CSS supplied by Mail Chimp 
- [ ] Manually Test form submission
- [ ] Add link to newsletter from Home Page 'About Us' section
