### ISSUE TITLE
Ability to add new products to shop

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#40]
As a website owner I can add a new product to the shop so that I can sell the product to customers

## Acceptance Criteria:
a) When the admin user is logged in, they have an option under the Account menu for Product Management
b) When they go to this page, there is a form to Add a Product
c) The fields on the form are: category dropdown, sku, name, description, price, image and check boxes for active product and new product
d) The product name must not be the same as an existing product name
e) The active and new checkboxes default to checked and the image field is optional (as the no-image file will show up for the product if there is no image attached)
f) After adding the product (and assuming the active flag is ticked), the product shows up in the shop page for users to buy

## Tasks:
- [ ] Create the product form
- [ ] Create the add_product view and URL 
- [ ] Add URL to the main header under Account dropdown if user is superuser
- [ ] Create the add_product.html template
- [ ] Update the view to handle posting the form
