### ISSUE TITLE
Edit Product in Shop

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#41]
As a website owner I can edit the details of a product in the shop so that I can change the price, description etc. and customers will see the updated information

## Acceptance Criteria:
a) When admin user is signed in, they can see an Edit link/button on the products in the shop on both the main shop page and in the product details page
b) Clicking the link brings them to the edit product page which displays a form with the existing details pre-populated
c) The user can change the details as needed and submit the form
d) Once submitted, the page redirects to the product details page for that product with the updated details

## Tasks:
- [ ] Create edit_product.html template
- [ ] Add CSS
- [ ] Create the view and the URL
- [ ] Add the URL link to the product card on the products page, and in product_details page
- [ ] Add the custom widget for the image upload field, update forms.py to use it
- [ ] Update the view to handle the post request
