### ISSUE TITLE
Delete a product from the site

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#43]
As a website owner I can delete a product so that it will not appear in the shop

## Acceptance Criteria:
a) When admin user is signed in, they can see a Delete link/button on the products in the shop on both the main shop page and in the product details page
b) Clicking the link brings up a confirmation box where they can either Cancel to go back, or press Confirm to confirm the deletion. The confirmation box shows the summary details of the product they are about to delete.
c) Once deleted, the product no longer appears in the shop

## Tasks:
- [ ] Create the view and the URL
- [ ] Create the delete HTML modal
- [ ] Add CSS as needed
- [ ] Add the delete link to the product and product_details template
