### ISSUE TITLE
Admin site for Products App

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#45]
As a site owner I can access the Django admin site for the products so that I can view, edit, delete products from here as well as from the website

## Acceptance Criteria:
a) The admin user can go to the Django admin site and view the products and categories tables inside the products app.
b) For the categories table, the category name and friendly name are displayed in the list view
c) For the products table, the list view shows product name, sku, category, price, if new, if active.
d) The user can add, edit and delete products and categories from this view (default Django functionality)
e) The user can amend the is_active flag from list view, and can search by product name

## Tasks:
- [x] Create superuser to access admin site, add site name to settings
- [x] Create admin class for category model in admin.py
- [ ] Create admin class for product model in admin.py
