### ISSUE TITLE
Custom 404 & 500 Page

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#5]
As a site user I can see a 'Page not found' page with consistent branding to the rest of the site, when I try to access a page in error so that I can find my way back to the website and know I have not left the website. Ensure page tells user which error they are getting.

## Acceptance Criteria:
a) The 404 page not found that is displayed to the user is consistent with the branding on the rest of the website
b) The 500 page error is displayed to the user and is consistent with the branding on the rest of the website
c) The page contains the header and footer as per the rest of the website

## Tasks:
- [ ] Create the html template
- [ ] Add any CSS as necessary 
- [ ] Ensure correct page displays for each scenario
