### ISSUE TITLE
Find terms of use and privacy policy

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#6]
As a site user I can find the terms of use and privacy policy so that I can read these documents and have trust in the site

## Acceptance Criteria:
a) The links to the Terms of Use and Privacy Policy are present in the footer on each page
b) The links are internal so open in same window
c) Each link contains the correct policy

## Tasks:
- [ ] Create appropriate template / URL / view
- [ ] Generate Privacy Policy
- [ ] Add Link to Footer
- [ ] Add CSS if needed
- [ ] Test page
