### ISSUE TITLE
Confirmation message upon action

### ISSUE THREAD

**Issue by RiyadhKh4n** [RiyadhKh4n/cmarket#8]
As a user I can see a message confirming my actions (e.g. adding item to bag) so that I know my changes were received

## Acceptance Criteria:
a) When a user performs actions that interact with the site, a message is displayed confirming the action was successful, or if there were errors
b) E.g. in the search box on Shop page, if no search items entered it generates an error message
c) Or for adding, removing, adjusting quantity of items in the shopping cart

## Tasks:
- [ ] Create HTML for messages (Bootstrap Toasts)
- [ ] Update base.html to include a container to show the messages, and include JS to call method
- [ ] Add CSS as required
- [ ] Update settings.py to store the messages in session
- [ ] Update the Views as appropriate
- [ ] Create Toasts folder and template
- [ ] Manually Test
